### ISSUE TITLE
Idea: allow setting URL, width and height from the URL (hash)

### ISSUE THREAD

**Issue by mathiasbynens** [remy/responsivepx#2]
E.g. `http://responsivepx.com/#1024x768` would prefill only the width and height fields, or `http://responsivepx.com/#1024x768xhttp%3A%2F%2Fwww.google.com%2F` would also load the given URL.

Thoughts?

**Comment by remy** [comment]
My thoughts: useful for to pass around to the CSS person to see where the breaking point is - I'd say that's useful.

Any specific reason you use # over ?.  No big deal really either way - just wondering.  For that kind of stuff, I tend to add it to the query string.  Can't right now remember why tho.

**Comment by remy** [comment]
How about: responsivepx.com?google.com#1024x768

And I'll add pushState support to change the url as the user makes changes.

**Comment by remy** [comment]
Actually, you also need whether they checked the scroll visible box too - because that modifies the values they're seeing.  Gotta hit the sack, but definitely up for adding that change.

**Comment by mathiasbynens** [comment]
Nice!
