### ISSUE TITLE
Less sensitive width/height sliders

### ISSUE THREAD

**Issue by Nettsentrisk** [remy/responsivepx#6]
The slider for the width doesn't let you fluidly adjust the width, it steps too far when you move it, typically ~100px at a time. To emulate how you would drag the window size of the browser, the slider should perhaps be a bit wider to allow for more careful adjustment?

Maybe the slider for width could be right above the viewport and span the full width of the screen, so there's a 1:1 relationship between the slider and the viewport width (and height?).

**Comment by remy** [comment]
Why not either focus the slider or the numerical field and use your cursor
keys? Up to increment, etc.

On Tuesday, August 20, 2013, George Gooding wrote:

> The slider for the width doesn't let you fluidly adjust the width, it
> steps too far when you move it, typically ~100px at a time. To emulate how
> you would drag the window size of the browser, the slider should perhaps be
> a bit wider to allow for more careful adjustment?
> 
> Maybe the slider for width could be right above the viewport and span the
> full width of the screen, so there's a 1:1 relationship between the slider
> and the viewport width (and height?).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/remy/responsivepx/issues/6
> .

## 

— Remy

**Comment by Nettsentrisk** [comment]
That doesn't emulate the (much quicker) resizing of a browser window. :)

Then again, I might as well just use http://screenqueri.es.
